#!/usr/bin/env bash

#
#	Script to create files, write a portable shebang to them, and then run chmod +x on them to make them executable
#	Usage: scriptmkr [FILE NAME]
#

if [ -z "$1" ]
then
	echo "Error! No filename provided. Usage: scriptmkr [FILENAME]"
	exit

fi
touch $1
echo "#!/usr/bin/env bash"> $1
chmod +x $1
